<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MusicStore.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MusicPlayer.Application\MusicPlayer.Application.csproj" />
      <ProjectReference Include="..\MusicPlayer.Domain\MusicPlayer.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NAudio" Version="2.3.0" />
    </ItemGroup>

</Project>
